version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - .env:/var/www/html/.env
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

