version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
