services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .env:/var/www/html/.env
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
