version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
